---
title: "Project BST 260"
author: "et al"
date: "November 20, 2018"
output: html_document
---

---
title: "Template"
author: "Anthony O'Brien"
date: "September 30, 2018"
output: html_document
---

#Packages and libraries
```{r}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("dplyr")
#install.packages("ggplot2")
##install.packages("bigrquery")
#install.packages("devtools")
#install.packages("MIMICbook")
library("dplyr")
library("ggplot2")
library("bigrquery")
library("devtools")
library("MIMICbook")
```

```{r, include = FALSE}
if(!("devtools" %in% installed.packages()[,1])) {install.packages("devtools",repos="https://cloud.r-project.org")}
if(!("MIMICbook" %in% installed.packages()[,1])) {install_github("jraffa/MIMICbook")}
```

#Function to import query from Big query SQL

```{r dbconnect, include=FALSE}
# Load configuration settings
project_id <- "hst-953-2018"
options(httr_oauth_cache=TRUE)
run_query <- function(query)
    {
    data <- query_exec(query, project=project_id, max_pages = Inf, use_legacy_sql = FALSE)
    return(data)
    }
```

#Save query to df in R and csv

```{r}
#sql query 
sql_query_eicu <- ""
```

```{r}
#Place MIMIC query into a dataframe
df<- run_query(sql_query_eicu)
```

```{r}
#save to a scv
write.csv(df,'df.csv')
```

