---
title: "Untitled"
output: html_document
---

```{r}
library(dplyr)
# load('../data/hds_1213.Rda')
# hds<-hds %>% unique()
```

```{r}
# data %>% summary()
```

```{r}
# imbalanced dataset : 8% of target ==1
sum(hds$icustay_expire_flag)/length(hds$icustay_expire_flag)

# columns to standardize
col_to_standardize <- colnames(hds)
col_to_standardize 
# hds

# features to delete
to_delete <- c("los_icu","los_hospital","intime","outtime","subject_id","hadm_id","icustay_id","admittime","religion","insurance","dischtime","ethnicity","admission_location","diagnosis","hospital_expire_flag","isnaintime","max","ICUSTAY_AGE_GROUP")

hds <- hds[,!colnames(hds) %in% to_delete]

# features that we don't want to standardize
# we keep icustay_expire_flag because it is the target to predict
not_to_standardize <- c("gender","first_icu_stay","AdmissionType_ELECTIVE","AdmissionType_EMERGENCY","AdmissionType_URGENT","icustay_expire_flag")

col_to_standardize <- colnames(hds)[!colnames(hds) %in% c(not_to_standardize,"icustay_id")]
col_to_standardize

# hds
```


Standardize data except icustay_id and icustay_expire_flag (target) and categorical features:
```{r}
library(caret)
preprocessParams <- preProcess(hds[,col_to_standardize], method=c("center", "scale"))
transformed <- predict(preprocessParams, hds[,col_to_standardize])
# transformed %>% head()
final <- cbind(transformed, hds[,not_to_standardize])
colnames(final) <- c(colnames(transformed),not_to_standardize)
final %>% head()
```

```{r}
library(FactoMineR)
res.pca = PCA(final[,1:62], scale.unit=TRUE, ncp=5, graph=T)
```

Data split:
```{r}
final[,"icustay_expire_flag"] <- factor(final[,"icustay_expire_flag"])
trainIndex <- createDataPartition(final$icustay_expire_flag, p=0.80, list=FALSE)
dataTrain <- final[ trainIndex,]
dataTest <- final[-trainIndex,]
```

Naive Bayes Classifier:
```{r}
library(klaR)
# train a naive Bayes model
fit <- NaiveBayes(icustay_expire_flag~., data=dataTrain)
# make predictions
predictions <- predict(fit, dataTest[,1:62])
# summarize results
confusionMatrix(predictions$class, dataTest$icustay_expire_flag)
```

```{r}
# Comparing with a random classifier
N <- length(data$icustay_id)
y_hat <- sample(c(0, 1), N, replace = TRUE)
table(predicted = y_hat, actual = data$icustay_expire_flag)
```


Undersampling of class 0 because we have an imbalanced dataset:
```{r}
# will work on that later
```

